export const headphones = [
  {
    img: "/images/Apple BYZ S852I.png",
    title: "Apple BYZ S852I",
    price: 2927,
    oldPrice: 3527,
    rate: 4.7,
    type: "wired",
    id: 1,
  },
  {
    img: "/images/Apple EarPods.png",
    title: "Apple EarPods",
    price: 2327,
    rate: 4.5,
    type: "wired",
    id: 2,
  },
  {
    img: "/images/Apple EarPods2.png",
    title: "Apple EarPods",
    price: 2327,
    rate: 4.5,
    type: "wired",
    id: 3,
  },
  {
    img: "/images/Apple AirPods.png",
    title: "Apple AirPods",
    price: 9527,
    rate: 4.5,
    type: "wireless",
    id: 4,
  },
  {
    img: "/images/GERLAX GH-04.png",
    title: "GERLAX GH-04",
    price: 6527,
    rate: 4.7,
    type: "wireless",
    id: 5,
  },
  {
    img: "/images/BOROFONE BO4.png",
    title: "BOROFONE BO4",
    price: 7527,
    rate: 4.7,
    type: "wireless",
    id: 6,
  },
];
